apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-pod
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do sleep 2; done"]
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    presistentVolumeClaim:
      claimName: storage-pvc
