apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb
spec:
  selector:
    app: dns
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
  - protocol: UDP
    port: 53
    targetPort: 53
