apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
metadata:
  name: config
apiServer:
  extraArgs:
    "feature-gates": "VolumeSnapshatDataSource=true"
scheduler:
  extraArgs:
    "feature-gates": "VolumeSnapshatDataSource=true"
controllerManager:
  extraArgs:
    "feature-gates": "VolumeSnapshatDataSource=true"

---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
metadata:
  name: config
nodeRegistration:
  kubletExtraArgs:
    "feature-gates": "VolumeSnapshatDataSource=true"
    