apiVersion: v1
kind: Pod
metadata:
  name: iscsi-pod
spec:
  containers:
  - name: isci-pod
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do sleep 2; done"]
    volumeMounts:
    - name: iscsipd-rw
      mountPath: /data
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 10.128.0.6:3260
      portals: ['10.128.0.6:3260']
      iqn: iqn.2003-01.org.linux-iscsi.instance-main.x8664:sn.1efa8fbe91d8
      lun: 1
      fsType: ext4
      readOnly: false